{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import kfp\n",
    "import kfp.dsl as dsl\n",
    "import kfp.gcp as gcp\n",
    "import kfp.compiler as compiler\n",
    "from kfp import components\n",
    "from kubernetes import client as k8s_client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    " @dsl.pipeline(\n",
    "    name='vq-vae_1d pipeline',\n",
    "    description='A pipeline to train vq-vae'\n",
    ")\n",
    "def vae_pipeline(\n",
    "    git_clone_dir: str=\"/home/jovyan/vq-vae_1d\",\n",
    "    repo_url: str='http://oauth2:GwpqNg4XFT3z-H5FTk7j@zaku.sys.es.osaka-u.ac.jp:10080/OHMORI/vq-vae_1d.git',\n",
    "    user_namespace = \"k-ohmori\",\n",
    "    repo_checkout: str=\"master\",\n",
    "    data_type: str='gaze',\n",
    "    f_name: str='vq_vae',\n",
    "    num_hiddens: int=32,\n",
    "    num_residual_hiddens: int=32,\n",
    "    num_residual_layers: int=2,\n",
    "    embedding_dim: int=8,\n",
    "    num_embeddings: int=128,\n",
    "    commitment_cost: float =0.25,\n",
    "    decay: float =0.99,\n",
    "    epoch: int=500,\n",
    "    lr: float = 1e-3,\n",
    "    batch_size: int=32,\n",
    "):    \n",
    "    #secret setting for pipeline\n",
    "    dsl.get_pipeline_conf().set_image_pull_secrets([k8s_client.V1LocalObjectReference(name=\"regcred\")])\n",
    "    #TTLの設定\n",
    "    dsl.get_pipeline_conf().set_ttl_seconds_after_finished(300)\n",
    "    \n",
    "    git_clone = dsl.UserContainer(\n",
    "        name='git-clone', \n",
    "        image='alpine/git:latest',\n",
    "        command = [\"sh\", \"-c\"],\n",
    "        args = [\n",
    "            \"git clone {0} {1}\".format(repo_url, git_clone_dir) + \\\n",
    "            \" && cd {0};\".format(git_clone_dir) + \\\n",
    "            \" git checkout {0}\".format(repo_checkout) + \\\n",
    "            \" && mkdir data\"\n",
    "        ],\n",
    "        mirror_volume_mounts=True\n",
    "    )\n",
    "\n",
    "\n",
    "    # Volume for storing Git repository (PV)\n",
    "#     volume_op = dsl.VolumeOp(\n",
    "#         name='create pipeline volume',\n",
    "#         resource_name='pipeline-pvc',\n",
    "#         modes=['ReadWriteMany'],\n",
    "#         size=\"1Gi\"\n",
    "#     )\n",
    "\n",
    "#     git_clone = git_clone_op(repo_url=repo_url, volume_op=volume_op)\n",
    "\n",
    "    container_op=dsl.ContainerOp(\n",
    "        name='VQ-VAE',\n",
    "        image='zaku.sys.es.osaka-u.ac.jp:10081/ohmori/vq-vae_1d:v0.0.0',\n",
    "        # command=['sh'],\n",
    "        # arguments=['-c', ' && '.join(commands)],\n",
    "        command=['python3', 'train.py'],\n",
    "        arguments=[\n",
    "            '--data_type', data_type,\n",
    "            '--f_name', f_name,\n",
    "            '--num_hiddens', num_hiddens,\n",
    "            '--num_residual_hiddens', num_residual_hiddens,\n",
    "            '--num_residual_layers', num_residual_layers,\n",
    "            '--embedding_dim', embedding_dim,\n",
    "            '--num_embeddings', num_embeddings,\n",
    "            '--commitment_cost', commitment_cost,\n",
    "            '--decay', decay,\n",
    "            '--epoch', epoch,\n",
    "            '--lr', lr,\n",
    "            '--batch_size', batch_size\n",
    "        ],\n",
    "#         pvolumes={'/home/jovyan': git_clone.pvolume},\n",
    "#         # output Tensorboard, 上手く動作しない\n",
    "#         file_outputs={\n",
    "#             'MLPipeline UI metadata': '/mlpipeline-ui-metadata.json'\n",
    "#         }\n",
    "    )\n",
    "    \n",
    "    # add rlg-private volume\n",
    "    nfs_volume_source = k8s_client.V1NFSVolumeSource(server=\"192.168.11.221\", path=\"/data/users/{}/vq-vae_data/k_ohmori/\".format(user_namespace))\n",
    "    container_op.add_volume(k8s_client.V1Volume(name='private', nfs=nfs_volume_source))\n",
    "    container_op.add_volume_mount(k8s_client.V1VolumeMount(mount_path='/home/jovyan/vq-vae_1d/data',name='logs'))\n",
    "\n",
    "    # train.add_pvolumes({'/workspace': git_clone.pvolume})\n",
    "    # train.add_volume_mount(volume_mount=k8s_client.V1VolumeMount(mount_path='/home/jovyan',name=git_clone.name))\n",
    "\n",
    "    #set nfs information and mount nfs on Container(named train)\n",
    "#     nfs_volume_source = k8s_client.V1NFSVolumeSource(server=\"192.168.11.107\", path=\"/data/share/data\")\n",
    "#     train.add_volume(k8s_client.V1Volume(name='data', nfs=nfs_volume_source))\n",
    "#     train.add_volume_mount(k8s_client.V1VolumeMount(mount_path='/home/jovyan/vq-vae_1d/data',name='data'))\n",
    "\n",
    "#     nfs_volume_source = k8s_client.V1NFSVolumeSource(server=\"192.168.11.107\", path=\"/data/share/pth\")\n",
    "#     train.add_volume(k8s_client.V1Volume(name='pth', nfs=nfs_volume_source))\n",
    "#     train.add_volume_mount(k8s_client.V1VolumeMount(mount_path='/home/jovyan/vq-vae_1d/script/pth',name='pth'))\n",
    "\n",
    "#     nfs_volume_source = k8s_client.V1NFSVolumeSource(server=\"192.168.11.107\", path=\"/data/share/logs\")\n",
    "#     train.add_volume(k8s_client.V1Volume(name='logs', nfs=nfs_volume_source))\n",
    "#     train.add_volume_mount(k8s_client.V1VolumeMount(mount_path='/home/jovyan/vq-vae_1d/script/logs',name='logs'))\n",
    "\n",
    "#     train.add_volume(k8s_client.V1Volume(name=\"dshm\", empty_dir=k8s_client.V1EmptyDirVolumeSource(medium=\"Memory\")))\n",
    "#     train.add_volume_mount(k8s_client.V1VolumeMount(mount_path='/dev/shm',name='dshm'))\n",
    "\n",
    "#     #set workdirectory\n",
    "#     train.container.working_dir = \"/home/jovyan/vq-vae_1d/script\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Failed to get healthz info attempt 1 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp/_client.py\", line 312, in get_kfp_healthz\n",
      "    response = self._healthz_api.get_healthz()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 77, in get_healthz\n",
      "    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 162, in get_healthz_with_http_info\n",
      "    collection_formats=collection_formats)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 383, in call_api\n",
      "    _preload_content, _request_timeout, _host)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 202, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 199, in __call_api\n",
      "    _request_timeout=_request_timeout)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 407, in request\n",
      "    headers=headers)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 248, in GET\n",
      "    query_params=query_params)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 238, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (403)\n",
      "Reason: Forbidden\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 06 Sep 2021 13:18:21 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})\n",
      "HTTP response body: RBAC: access denied\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 2 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp/_client.py\", line 312, in get_kfp_healthz\n",
      "    response = self._healthz_api.get_healthz()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 77, in get_healthz\n",
      "    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 162, in get_healthz_with_http_info\n",
      "    collection_formats=collection_formats)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 383, in call_api\n",
      "    _preload_content, _request_timeout, _host)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 202, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 199, in __call_api\n",
      "    _request_timeout=_request_timeout)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 407, in request\n",
      "    headers=headers)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 248, in GET\n",
      "    query_params=query_params)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 238, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (403)\n",
      "Reason: Forbidden\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 06 Sep 2021 13:18:26 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})\n",
      "HTTP response body: RBAC: access denied\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 3 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp/_client.py\", line 312, in get_kfp_healthz\n",
      "    response = self._healthz_api.get_healthz()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 77, in get_healthz\n",
      "    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 162, in get_healthz_with_http_info\n",
      "    collection_formats=collection_formats)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 383, in call_api\n",
      "    _preload_content, _request_timeout, _host)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 202, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 199, in __call_api\n",
      "    _request_timeout=_request_timeout)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 407, in request\n",
      "    headers=headers)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 248, in GET\n",
      "    query_params=query_params)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 238, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (403)\n",
      "Reason: Forbidden\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 06 Sep 2021 13:18:31 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})\n",
      "HTTP response body: RBAC: access denied\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 4 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp/_client.py\", line 312, in get_kfp_healthz\n",
      "    response = self._healthz_api.get_healthz()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 77, in get_healthz\n",
      "    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 162, in get_healthz_with_http_info\n",
      "    collection_formats=collection_formats)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 383, in call_api\n",
      "    _preload_content, _request_timeout, _host)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 202, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 199, in __call_api\n",
      "    _request_timeout=_request_timeout)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 407, in request\n",
      "    headers=headers)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 248, in GET\n",
      "    query_params=query_params)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 238, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (403)\n",
      "Reason: Forbidden\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 06 Sep 2021 13:18:36 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})\n",
      "HTTP response body: RBAC: access denied\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 5 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp/_client.py\", line 312, in get_kfp_healthz\n",
      "    response = self._healthz_api.get_healthz()\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 77, in get_healthz\n",
      "    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api/healthz_service_api.py\", line 162, in get_healthz_with_http_info\n",
      "    collection_formats=collection_formats)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 383, in call_api\n",
      "    _preload_content, _request_timeout, _host)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 202, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 199, in __call_api\n",
      "    _request_timeout=_request_timeout)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/api_client.py\", line 407, in request\n",
      "    headers=headers)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 248, in GET\n",
      "    query_params=query_params)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/kfp_server_api/rest.py\", line 238, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (403)\n",
      "Reason: Forbidden\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Mon, 06 Sep 2021 13:18:41 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})\n",
      "HTTP response body: RBAC: access denied\n",
      "\n"
     ]
    },
    {
     "ename": "TimeoutError",
     "evalue": "Failed getting healthz endpoint after 5 attempts.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTimeoutError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-12-ea0e359f4eb9>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m }\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0mkfp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"ml-pipeline.kubeflow.svc.cluster.local:8888\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnamespace\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"k-ohmori\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mset_user_namespace\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"k-ohmori\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      8\u001b[0m kfp.Client(host=\"ml-pipeline.kubeflow.svc.cluster.local:8888\", namespace=\"k-ohmori\").create_run_from_pipeline_package(\n\u001b[1;32m      9\u001b[0m     \u001b[0mpipeline_file\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"/tmp/pipelines.yaml\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/lib/python3.7/site-packages/kfp/_client.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, host, client_id, namespace, other_client_id, other_client_secret, existing_token, cookies, proxy, ssl_ca_cert, kube_context)\u001b[0m\n\u001b[1;32m    146\u001b[0m     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_upload_api\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mkfp_server_api\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mapi\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPipelineUploadServiceApi\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mapi_client\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    147\u001b[0m     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_healthz_api\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mkfp_server_api\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mapi\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhealthz_service_api\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mHealthzServiceApi\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mapi_client\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 148\u001b[0;31m     \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_context_setting\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'namespace'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_kfp_healthz\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmulti_user\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    149\u001b[0m       \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    150\u001b[0m         \u001b[0;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mClient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mNAMESPACE_PATH\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'r'\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/lib/python3.7/site-packages/kfp/_client.py\u001b[0m in \u001b[0;36mget_kfp_healthz\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    308\u001b[0m       \u001b[0mcount\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    309\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mcount\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0mmax_attempts\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 310\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mTimeoutError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Failed getting healthz endpoint after {} attempts.'\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmax_attempts\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    311\u001b[0m       \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    312\u001b[0m         \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_healthz_api\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_healthz\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTimeoutError\u001b[0m: Failed getting healthz endpoint after 5 attempts."
     ]
    }
   ],
   "source": [
    "compiler.Compiler().compile(vae_pipeline,\"/tmp/pipelines.yaml\")\n",
    "arguments={\n",
    "    \"user_namespace\":\"k-ohmori\",\n",
    "    \"data_type\": \"gsr\"\n",
    "}\n",
    "\n",
    "kfp.Client(host=\"ml-pipeline.kubeflow.svc.cluster.local:8888\", namespace=\"k-ohmori\").set_user_namespace(\"k-ohmori\")\n",
    "kfp.Client(host=\"ml-pipeline.kubeflow.svc.cluster.local:8888\", namespace=\"k-ohmori\").create_run_from_pipeline_package(\n",
    "    pipeline_file=\"/tmp/pipelines.yaml\",\n",
    "    run_name=\"vq-vae_1d pipeline\",\n",
    "    arguments=arguments,\n",
    "    experiment_name=\"vq-vae_1d\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
